#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

if [ -w /sys/kernel/uevent_helper ]; then
	echo > /sys/kernel/uevent_helper
fi

if [ "${quiet:-n}" = "y" ]; then
	log_level=notice
else
	log_level=info
fi

SYSTEMD_LOG_LEVEL=$log_level /usr/lib/systemd/systemd-udevd --daemon --resolve-names=never

udevadm trigger --type=subsystems --action=add
udevadm trigger --type=devices --action=add

# Not use udevadm settle to wait
#udevadm settle || true
root_uuid=${ROOT#UUID=}
for i in $( seq 1 25 )
do
        rootdev="$(blkid --uuid "${root_uuid}")"
        if [ -n "${rootdev}" ];then
                break
        fi
                sleep 0.2
done

# Leave udev running to process events that come in out-of-band (like USB
# connections)
